In [1]:
import numpy as np

In [2]:
H = np.array([[0,   0, 1/3, 0],
              [1/2, 0, 1/3, 0],
              [1/2, 0, 0,   1],
              [0,   1, 1/3, 0]])

In [3]:
PR0=np.array([1/4,1/4,1/4,1/4]).reshape(-1,1)

In [4]:
np.dot(H, PR0)

array([[0.08333333],
       [0.20833333],
       [0.375     ],
       [0.33333333]])

In [5]:
eigen_value, eigen_vector = np.linalg.eig(H)
eigen_value

array([ 1.        +0.j        , -0.62653829+0.j        ,
       -0.18673085+0.48077388j, -0.18673085-0.48077388j])

In [6]:
eigen_vector

array([[-0.23249528+0.j        ,  0.44574718+0.j        ,
         0.14649706+0.37718437j,  0.14649706-0.37718437j],
       [-0.34874292+0.j        ,  0.09002496+0.j        ,
         0.43592932+0.11241445j,  0.43592932-0.11241445j],
       [-0.69748583+0.j        , -0.83783303+0.j        ,
        -0.62608774+0.j        , -0.62608774-0.j        ],
       [-0.58123819+0.j        ,  0.30206089+0.j        ,
         0.04366137-0.48959882j,  0.04366137+0.48959882j]])

In [7]:
np.abs(np.real(eigen_vector[:,0]))

array([0.23249528, 0.34874292, 0.69748583, 0.58123819])

In [8]:
theta = np.array([[-1,2,2],
                  [ 2,1,0],
                  [ 2,0,1]])

In [9]:
eig_val, eig_vec = np.linalg.eig(theta)

In [10]:
eig_val

array([-3.,  3.,  1.])

In [11]:
eig_vec

array([[ 8.16496581e-01, -5.77350269e-01, -7.85046229e-17],
       [-4.08248290e-01, -5.77350269e-01, -7.07106781e-01],
       [-4.08248290e-01, -5.77350269e-01,  7.07106781e-01]])

In [12]:
H = np.array([[0.65,0.28,0.07],
             [0.15,0.67,0.18],
             [0.12,0.36,0.52]])
d0 = np.array([[0.21,0.68,0.11]])

In [13]:
np.linalg.eig(H)

(array([1.        , 0.51848858, 0.32151142]),
 array([[-0.57735027, -0.83998777,  0.28556198],
        [-0.57735027,  0.27803966, -0.53396905],
        [-0.57735027,  0.46595546,  0.79582121]]))

In [14]:
di = d0
for i in range(1, 11):
    dn = np.dot(di, H)
    di = dn
    print('{}:{}'.format(i, np.round(di,6)))

1:[[0.2517 0.554  0.1943]]
2:[[0.270021 0.511604 0.218375]]
3:[[0.278459 0.496996 0.224545]]
4:[[0.282493 0.491792 0.225715]]
5:[[0.284475 0.489856 0.225669]]
6:[[0.285468 0.489097 0.225435]]
7:[[0.285971 0.488783 0.225247]]
8:[[0.286228 0.488645 0.225127]]
9:[[0.28636  0.488582 0.225058]]
10:[[0.286428 0.488552 0.22502 ]]


In [15]:
P = np.array([[0.5,0.5],
             [0.1,0.9]])
p0 = np.array([100,0])

In [16]:
np.linalg.eig(P)

(array([0.4, 1. ]),
 array([[-0.98058068, -0.70710678],
        [ 0.19611614, -0.70710678]]))

In [17]:
pi = p0
for i in range(1, 11):
    pn = np.dot(pi, P)
    print('{}:{} {} {}'.format(i, np.round(pi,6), np.round(pi[0]*0.5,4), np.round(pi[1]*0.4)))
    pi = pn

1:[100   0] 50.0 0.0
2:[50. 50.] 25.0 20.0
3:[30. 70.] 15.0 28.0
4:[22. 78.] 11.0 31.0
5:[18.8 81.2] 9.4 32.0
6:[17.52 82.48] 8.76 33.0
7:[17.008 82.992] 8.504 33.0
8:[16.8032 83.1968] 8.4016 33.0
9:[16.72128 83.27872] 8.3606 33.0
10:[16.688512 83.311488] 8.3443 33.0
