In [27]:
import tensorflow as tf

In [28]:
tf.__version__

'2.0.0'

In [29]:
tf.executing_eagerly()

True

In [30]:
x = [[2,]]

In [31]:
m = tf.matmul(x, x)

In [32]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [33]:
m.numpy()

array([[4]])

In [34]:
a = tf.constant([[1, 2],[3, 4]])

In [35]:
a

<tf.Tensor: id=44, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]])>

In [36]:
b = tf.add(a, 1)

In [37]:
b

<tf.Tensor: id=46, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]])>

In [38]:
import numpy as np

In [39]:
d = np.array([[5,6],[7,8]])

In [40]:
d

array([[5, 6],
       [7, 8]])

In [41]:
(a + b).numpy()

array([[3, 5],
       [7, 9]])

In [42]:
a + b

<tf.Tensor: id=48, shape=(2, 2), dtype=int32, numpy=
array([[3, 5],
       [7, 9]])>

In [43]:
c = tf.multiply(a,b)

In [44]:
c

<tf.Tensor: id=49, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]])>

In [45]:
num = tf.convert_to_tensor(10)

In [46]:
num

<tf.Tensor: id=50, shape=(), dtype=int32, numpy=10>

In [47]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
