In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
tf.executing_eagerly()

True

In [5]:
x = [[2, ]]

In [6]:
m = tf.matmul(x, x)

In [9]:
print(m)

tf.Tensor([[4]], shape=(1, 1), dtype=int32)


In [10]:
m.numpy()

array([[4]], dtype=int32)

In [12]:
a = tf.constant([[1,2],[3,4]])

In [23]:
a

<tf.Tensor: id=3, shape=(2, 2), dtype=int32, numpy=
array([[1, 2],
       [3, 4]], dtype=int32)>

In [24]:
import numpy as np

In [25]:
d = np.array([[5,6],
                   [7,8]])

In [26]:
d

array([[5, 6],
       [7, 8]])

In [29]:
(a + d).numpy()

array([[ 6,  8],
       [10, 12]], dtype=int32)

In [15]:
b = tf.add(a,1)

In [16]:
b

<tf.Tensor: id=5, shape=(2, 2), dtype=int32, numpy=
array([[2, 3],
       [4, 5]], dtype=int32)>

In [17]:
c = tf.multiply(a, b)

In [18]:
c

<tf.Tensor: id=6, shape=(2, 2), dtype=int32, numpy=
array([[ 2,  6],
       [12, 20]], dtype=int32)>

In [19]:
num = tf.convert_to_tensor(10)

In [32]:
num

<tf.Tensor: id=7, shape=(), dtype=int32, numpy=10>

In [33]:
float(num)

10.0

In [22]:
for i in range(num.numpy()):
    i = tf.constant(i)
    if int(i%2) == 0:
        print('even')
    else:
        print('odd')

even
odd
even
odd
even
odd
even
odd
even
odd
