In [1]:
import numpy as np

In [2]:
def conjugate_gradient(A, b):
    
    n = b.shape[0]
    
#     x0 = np.array([2,1])
#     x0 = np.random.rand(b.shape[0])
    
    x0 = np.array(([2],[1]))
#     x0 = np.random.rand(b.shape[0],1)
    
    r0 = b - np.dot(A, x0)
    p0 = r0
    
    x_history = []
    p_history = []
    r_history = []
    alpha_history = []
    
    x_history.append(x0)
    p_history.append(p0)
    r_history.append(r0)
    
    for i in range(n):
        
        alpha = np.dot(p_history[i].T, r_history[i]) / p_history[i].T.dot(A).dot(p_history[i])
        r = r_history[i] - alpha * A.dot(p_history[i])
        beta = np.dot(r.T, r) / np.dot(r_history[i].T, r_history[i])
        p = r + beta * p_history[i]
        x = x_history[i] + alpha * p_history[i]
        
        r_history.append(r)
        alpha_history.append(alpha)
        p_history.append(p)
        x_history.append(x)
        
    return x_history

In [3]:
A = np.array(([4,1],[1,3]))
b = np.array(([1,2]))
c = np.array(([1],[2]))

In [4]:
np.linalg.inv(A).dot(b)

array([0.09090909, 0.63636364])

In [5]:
np.linalg.inv(A).dot(c)

array([[0.09090909],
       [0.63636364]])

In [6]:
conjugate_gradient(A, b)

[array([[2],
        [1]]),
 array([[0.26086957, 0.47435897],
        [0.12820513, 0.34339623]]),
 array([[0.18060662, 0.36213535],
        [0.27445501, 0.54796513]])]

In [7]:
conjugate_gradient(A, c)

[array([[2],
        [1]]),
 array([[0.23564955],
        [0.33836858]]),
 array([[0.09090909],
        [0.63636364]])]